llm:
  provider: anyscale
  api_key: esecret_pt7pwklepatz6w5dt7eflrharn
  model: mistralai/Mixtral-8x7B-Instruct-v0.1
  model_kwargs:
    temperature: 0.7
    #max_tokens: 8000
database:
  provider: postgres
  dbname: postgres
  host: localhost
  port: 5432
  user: postgres
  password: mysecretpassword
  # user_env: USR_ENV_VAR
  # password_env: PWD_ENV_VAR